### ISSUE TITLE
All fish are the same size, all larger than you

### ISSUE THREAD

**Issue by jonascarpay** [jonascarpay/SEM_46#49]

**Comment by Tclv** [comment]
<img width="579" alt="screen shot 2015-09-25 at 16 42 49" src="https://cloud.githubusercontent.com/assets/5967501/10103477/7db0a36c-63a4-11e5-8699-a41c81a5c1a7.png">

Problem lies in these lines. If the bounding box of the fish is out of the field the field automatically removes it. Either need to spawn fish in the field or add a flag that prohibits them from being killed of before entering field. Can also check for direction as well as whether it is in the field. Suggestions?

**Comment by ashay123** [comment]
Maybe we could just for now remove the player.getSize();, and fix it after the deadline, so that we have a working version?
