### ISSUE TITLE
Checkstyle errors for a multitude of files

### ISSUE THREAD

**Issue by Tclv** [jonascarpay/SEM_46#59]
Needs to be fixed (preferably in seperate pull requests as to avoid merge conflicts).

**Comment by jonascarpay** [comment]
We need to decide on a style before fixing this, I suggest we talk about this next tuesday

**Comment by ymte** [comment]
omdat we hier niet kunnen zijn, wat voor stijl doen we? 2 spaties/4 spaties?

**Comment by ymte** [comment]
Een style voor te importeren met eclipse (Window > Preferences > Java > Code Style > Formatter > Import...)
Als er nog dingen toe te voegen zijn doe snel
Gebruikt nu 4 spaties i.v.m. checkstyle
[STYLE.XML.txt](https://github.com/jonascarpay/SEM_46/files/4283/STYLE.XML.txt)

**Comment by ymte** [comment]
PS hernoem naar .xml, dit ondersteunt geen .xml

**Comment by jonascarpay** [comment]
<img width="1160" alt="screen shot 2015-09-29 at 19 26 03" src="https://cloud.githubusercontent.com/assets/3593851/10172501/f24d1b4a-66df-11e5-8549-2a959f589a59.png">
Dit lossen we niet op door af te spreken hoe we onze indentation doen

**Comment by jonascarpay** [comment]
Fixed by #68
